version: '3.9'

services:
  db:
    image: postgres
    env_file:
    - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U drupal"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - database-data:/var/lib/postgresql/data/
    networks:
    - elasticsearch

  drupal-init:
    env_file:
    - .env
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: /opt/docker/site-install.sh
    depends_on:
      db:
        condition: service_healthy
    networks:
      - elasticsearch

  drupal:
    env_file:
    - .env
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
    - 9998:80
    depends_on:
      db:
        condition: service_healthy
    volumes:
    - ./composer.lock:/opt/drupal/composer.lock
    - ./composer.json:/opt/drupal/composer.json
    - drupal-log:/var/log/apache2/
    networks:
      - elasticsearch

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:v1.0.1
    ports:
    - 8025:8025
    - 1025:1025

  memcached:
    image: memcached:latest
    ports:
    - 11211:11211

  elasticsearch:
    image: elasticsearch:7.14.0
    environment:
    - "discovery.type=single-node"
    - "bootstrap.memory_lock=true"
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
    - 9200:9200
    - 9300:9300
    networks:
    - elasticsearch

  kibana:
    image: kibana:7.14.0
    env_file:
      - .env
      - dev-environment/elk.env
    ports:
    - 5601:5601
    volumes:
      - ./kibana/config/:/usr/share/kibana/config/:ro
    depends_on:
    - elasticsearch
    networks:
    - elasticsearch

  logstash:
    build:
      context: logstash
    env_file:
      - .env
      - dev-environment/elk.env
    ports:
      - 9600:9600
      - 8089:8089
    volumes:
      - ./logstash/config/logstash1.conf:/usr/share/logstash/pipeline/logstash1.conf:ro
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/config/logstash3.conf:/usr/share/logstash/pipeline/logstash3.conf:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - db
      - elasticsearch
    networks:
      - elasticsearch

volumes:
  database-data:
  drupal-log:

networks:
  elasticsearch:
    driver: bridge
